---
functional:
  - Решение задач на скорость (против другого игрока/друга/бота)
  - Оба игрока могут видеть друг у друга редактор с кодом
  - Можно менять язык программирования
  - Можно выбрать сложность задачи
  - Выбрать определенную задачу или наугад
  - Следить за ходом решения
  - Можно общаться зарегистрированными пользователями
  - Просмотр завершенных игр
  - Просмотр рейтинга (за неделю/месяц/всё время)
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - попробовать игру без регистрации
  - переключать язык задачи на английский и русский
  - возможность сдаться
  - возможность сбросить решение
  - получение достижений
  - создание турниров
  - можно создать новую задачу
